### ISSUE TITLE
docker-compose file for deployment of `docs`

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/swarmauri-sdk#1240]
### Documentation Section

we need to orchestrate the deployment of `swarmauri-docs` using `npm`.

### Current Issue

We need to orchestrate two containers using docker-compose: one for the mkdocs-based documentation website (built from the provided Dockerfile) and one for the NGINX Proxy Manager (npm) to handle proxying, SSL termination, and routing.

### Suggested Improvement

We can use the docker-compose configuration below:

```yaml
version: '3.8'
services:
  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    container_name: mkdocs-docs
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: unless-stopped
    networks:
      - docs-network

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./mnt/data/nginx-proxy-manager:/data
      - ./mnt/data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    networks:
      - docs-network

networks:
  docs-network:
    driver: bridge

volumes:
```
