### ISSUE TITLE
GH workflow

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/swarmauri-sdk#1241]
### Documentation Section

`/docs`

### Current Issue

We need to add a workflow for documentation auto deployment. We can use the GitHub Actions workflow below to automate our CI/CD pipeline. 

### Suggested Improvement

```yaml
name: CI/CD Pipeline

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "Setting up build environment..."
          # Add commands to install dependencies, e.g., Python, Docker, etc.
          python --version
          docker --version

      - name: Build Docker network
        run: |
          echo "Building Docker Compose..."
          docker-compose build


      - name: Deploy application (Production or Staging)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging')
        run: |
                     docker-compose up
```
