### ISSUE TITLE
[Enhancement Request]: Transitioning from pip and setup.py to Poetry

### ISSUE THREAD

**Issue by MichaelDecent** [swarmauri/swarmauri-sdk#623]
### Feature/Enhancement Name

Transitioning from pip and setup.py to Poetry

### Enhancement Description

Switching from `setup.py` to Poetry for managing multiple packages 

### Motivation

We are currently experiencing dependency hell. frequent workflow failure during package installations, Here is why we need `Poetry`

**Simplified Dependency Management**

**Poetry Advantage:**

- **Unified Configuration:** Poetry uses a single pyproject.toml file to manage both your project’s metadata and dependencies, reducing the need to maintain separate files like setup.py, requirements.txt, and MANIFEST.in.

- **Semantic Versioning:** Poetry supports semantic versioning out of the box, making it easier to specify compatible dependency versions using operators like ^, ~, etc.

- **Automatic Dependency Resolution:** Poetry intelligently resolves and locks dependencies to ensure consistent environments across different machines and CI/CD pipelines, minimizing the infamous "it works on my machine" problem.

### Potential Solutions

Switching from setup.py to Poetry for managing multiple packages involves several steps to ensure a smooth transition. Below is a comprehensive, step-by-step guide to help you migrate your three-package project to Poetry.

**Prerequisites**

Install Poetry: Ensure you have Poetry installed on your system. If not, you can install it using the following command:
```
curl -sSL https://install.python-poetry.org | python3 -
```

After installation, ensure Poetry's bin directory is in your PATH. You can verify the installation by running:

```
poetry --version
```

Backup Your Project: Before making any changes, it's a good practice to back up your project or ensure it's version-controlled (e.g., using Git).

**Step-by-Step Migration Guide**

1. **Understand Your Project Structure**

our current project has the following structure:

```
swarmauri-sdk/pkgs/
├── swarmauri_community/
│   ├── setup.py
│   └── ... (other files)
├── swarmauri_core/
│   ├── setup.py
│   └── ... (other files)
├── swarmauri/
│   ├── setup.py
│   └── ... (other files)
└── README.md
```
2. **Initialize Poetry in Each Package**

For each package (package1, package2, package3), perform the following steps:

**a. Navigate to the Package Directory**
```
cd swarmauri-sdk/-pkgs/swarmauri
```

**b. Initialize Poetry**

Run the following command to initialize a new Poetry project. Poetry will prompt you for details; you can accept the defaults or input as necessary.

```
poetry init
```

Alternatively, to initialize with default settings and no prompts:

```
poetry init --no-interaction
```
This command creates a pyproject.toml file in the package directory.

**c. Migrate Dependencies**

Extract Dependencies from `setup.py`:

Open `setup.py `and locate the` install_requires` section. For example:

 `python`
```
install_requires=[
    "requests>=2.25.1",
    "numpy==1.19.5",
    # ... other dependencies
],
```
Add Dependencies to `pyproject.toml`:

Use Poetry to add each dependency. For example:

`bash`
```
poetry add requests@^2.25.1 numpy@1.19.5
```

Repeat this for all dependencies listed in `install_requires`.

Handle Development Dependencies:

If your `setup.py` has a `extras_require` or separate development dependencies, add them using:

`bash`
```
poetry add --dev pytest black
```
**d. Configure Package Metadata**

Ensure that the `pyproject.toml` has all necessary metadata that was previously in `setup.py`, such as:

    name
    version
    description
    authors
    license

You can edit `pyproject.toml` manually or use Poetry commands. For example:

`bash`
```
poetry config name "package1"
poetry config version "0.1.0"
poetry config description "Description of package1"
poetry config authors "Your Name <you@example.com>"
poetry config license "MIT"
```

Alternatively, edit the `pyproject.toml` directly:

`toml`
```
[tool.poetry]
name = "package1"
version = "0.1.0"
description = "Description of package1"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
numpy = "1.19.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^22.3.0"
```
**e. Handle Entry Points and Scripts**

If your `setup.py` defines entry points or console scripts, migrate them to `pyproject.toml` under `[tool.poetry.scripts]`. For example:

`python`
```
# setup.py
entry_points={
    'console_scripts': [
        'mycli=package1.module:main_function',
    ],
},
```
Convert to `pyproject.toml`:

`toml`
```
[tool.poetry.scripts]
mycli = "package1.module:main_function"
```
f. Remove `setup.py`

After migrating all necessary information to pyproject.toml, you can safely remove the setup.py file:

`bash`
```
rm setup.py
```
**g. Repeat for All Packages**

Perform steps `a` through `f` for other packages .

**3. Manage Inter-Package Dependencies**

If your packages depend on each other, you need to handle these dependencies appropriately.

**a. Use Local Path Dependencies**

Assuming `swamauri_core` pkg depends on `swamauri` pkg, and both are part of the same repository, you can specify the dependency using a relative path.

In `swamauri_core/pyproject.toml:
`
`toml`
```
[tool.poetry.dependencies]
package2 = { path = "../package2", develop = true }
```

Repeat this for any inter-package dependencies.

**b. Configure a Poetry Workspace (Optional)**

For better management of multiple packages, consider using a Poetry workspace.

    Create a Root ` pyproject.toml`:

    In my_project/, create a `pyproject.toml ` with the workspace configuration:

`toml`
```
[tool.poetry]
name = "my_project"
version = "0.1.0"
description = "My multi-package project"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^22.3.0"

[tool.poetry.group.dev.dependencies]
# Any additional dev dependencies

[workspace]
members = [
    "package1",
    "package2",
    "package3"
]
```
Initialize the Workspace:

Run the following command in the root directory:

`bash`
```
poetry install
```
 This will set up the workspace and install dependencies for all member packages.

**4. Update Version Control**

Ensure all changes are reflected in your version control system.

`bash`
```
git add .
git commit -m "Migrate from setup.py to Poetry for all packages"
```
**5. Adjust Continuous Integration (CI) and Deployment Pipelines**

If you have CI/CD pipelines, update them to use Poetry for dependency management and installation. For example, in a GitHub Actions workflow:

`yaml`
```
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "::add-path::$(python3 -m site --user-base)/bin"

    - name: Install Dependencies
      run: poetry install

    - name: Run Tests
      run: poetry run pytest
```

**6. Test the Migration**

    Install Dependencies:

    In each package directory, run:

    `bash`
```
poetry install
```
Or, if using a workspace, run this in the root directory.

Run Tests:

Ensure all tests pass to verify that dependencies are correctly managed.

Build and Publish (Optional):

Test building the packages with Poetry:

`bash`
```
poetry build
```
If everything works as expected, you can publish your packages:

`bash`
```
poetry publish
```
Ensure you have configured your PyPI credentials with Poetry before publishing.

Additional Tips

Lock Files: Poetry generates a poetry.lock file to ensure consistent dependencies across environments. Commit this file to version control.

Virtual Environments: Poetry manages virtual environments automatically. You can activate the virtual environment with:

`bash`
```
poetry shell
```
Updating Dependencies: Use poetry update to update dependencies as needed.

Documentation: Refer to the Poetry Documentation for advanced configurations and troubleshooting.

### Additional Context (optional)

A Video explaining how to implement poetry
https://www.youtube.com/watch?v=Ji2XDxmXSOM
https://www.youtube.com/watch?v=V5rKVrVhEh8

After the whole poetry adoption this could be our updated` staging.yml` file

```
name: Test Staging

on:
  pull_request:
    branches: ["staging", "*dev*"]
    paths:
      - 'pkgs/community/**'
      - 'pkgs/core/**'
      - 'pkgs/experimental/**'
      - 'pkgs/partners/**'
      - 'pkgs/swarmauri/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v3
      - name: Detect Changed Packages
        id: packages
        run: |
          git fetch origin ${{ github.event.before }}
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          CHANGED_PACKAGES=$(cat changed_files.txt | grep -oE '^pkgs/(community|core|experimental|partners|swarmauri)' | cut -d/ -f2 | sort -u | tr '\n' ',' | sed 's/,$//')
    
          if [ -z "$CHANGED_PACKAGES" ]; then
            # If no packages changed, set to an empty array
            CHANGED_PACKAGES_ARRAY="[]"
          else
            # Convert the comma-separated packages to a JSON array format
            CHANGED_PACKAGES_ARRAY=$(echo "[\"$(echo $CHANGED_PACKAGES | sed 's/,/","/g')\"]")
          fi

          # Export it to GITHUB_OUTPUT in JSON format
          echo "packages=$CHANGED_PACKAGES_ARRAY"
          echo "packages=$CHANGED_PACKAGES_ARRAY" >> $GITHUB_OUTPUT

  test:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        package: ${{ fromJSON(needs.detect-changes.outputs.packages) }}
    if: ${{ needs.detect-changes.outputs.packages != '[]' }}

    env:
      # (Your existing environment variables remain unchanged)
      AI21STUDIO_API_KEY: ${{ secrets.AI21STUDIO_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      DEEPINFRA_API_KEY: ${{ secrets.DEEPINFRA_API_KEY }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      LEPTON_API_KEY: ${{ secrets.LEPTON_API_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      SHUTTLEAI_API_KEY: ${{ secrets.SHUTTLEAI_API_KEY }}
      
      # Database Keys
      CHROMADB_COLLECTION_NAME: ${{ secrets.CHROMADB_COLLECTION_NAME }}
      NEO4J_COLLECTION_NAME: ${{ secrets.NEO4J_COLLECTION_NAME }}
      NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
      NEO4J_URI: ${{ secrets.NEO4J_URI }}
      NEO4J_USER: ${{ secrets.NEO4J_USER }}
      PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
      QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
      QDRANT_COLLECTION_NAME: ${{ secrets.QDRANT_COLLECTION_NAME }}
      QDRANT_URL_KEY: ${{ secrets.QDRANT_URL_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      WEAVIATE_API_KEY: ${{ secrets.WEAVIATE_API_KEY }}
      WEAVIATE_URL: ${{ secrets.WEAVIATE_URL }}
      
      # GitHub Keys
      GITHUBTOOL_TEST_REPO_NAME: ${{ secrets.GITHUBTOOL_TEST_REPO_NAME }}
      GITHUBTOOL_TEST_REPO_OWNER: ${{ secrets.GITHUBTOOL_TEST_REPO_OWNER }}
      GITHUBTOOL_TEST_TOKEN: ${{ secrets.GITHUBTOOL_TEST_TOKEN }}
      
      # Miscellaneous Tokens
      DANGER_MASTER_PYPI_API_TOKEN: ${{ secrets.DANGER_MASTER_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: python-poetry/poetry-action@v2.4.2
        with:
          version: '1.5.1'  # Specify the Poetry version you want to use

      - name: Configure Poetry (Optional)
        run: |
          poetry config virtualenvs.in-project true
          # Add any other Poetry configurations here

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
            pkgs/${{ matrix.package }}/.venv
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/pkgs/' + matrix.package + '/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-

      - name: Install dependencies with Poetry
        run: |
          cd pkgs/${{ matrix.package }}
          poetry install --no-interaction --no-root

      - name: Lint with flake8
        run: |
          poetry run flake8 pkgs/${{ matrix.package }} --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 pkgs/${{ matrix.package }} --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build package with Poetry
        run: |
          cd pkgs/${{ matrix.package }}
          poetry build

      - name: Install package
        run: |
          LATEST_WHL=$(ls pkgs/${{ matrix.package }}/dist/*.whl | sort -V | tail -n 1)
          poetry add "pkgs/${{ matrix.package }}/dist/$LATEST_WHL" --no-root

      - name: Run tests with Poetry
        run: |
          poetry run pytest -v pkgs/${{ matrix.package }}/tests --junitxml=results.xml

      - name: Output test results for debugging
        run: |
          cat pkgs/${{ matrix.package }}/tests/results.xml

      - name: Classify test results
        run: |
          poetry run python scripts/classify_results.py pkgs/${{ matrix.package }}/tests/results.xml
        continue-on-error: false
```

### Affected Areas

None

### Priority

Low
